### ISSUE TITLE
Update Language on Donate Page 

### ISSUE THREAD

**Issue by staceyturnage** [girldevelopit/gdi-new-site#197]
Description
Reword the verbiage on the donate page 

Ask
The wording is choppy & inconsistent. 

To Do
Update the donate page 

Reword the sentence
If you want to contribute to the success of women in technology and women transitioning into technology careers today, your contribution will help us improve the technology’s industry’s diversity problem, NOW! 
Girl Develop It appreciates all contributions from individuals and companies regardless of the amount. We put them to good use by providing a cost effective avenue for women to gain technical knowledge. By supporting Girl Develop It you are supporting the idea of it never being too late to learn. Girl Develop It engages students from ages 18-70 and we firmly believe there should be avenues for women to benefit from the opportunities and rewards by learning web development. 

Additional Info
Update verbiage.

**Comment by Roenok** [comment]
@corinnepw Copying you so HQ can review this language.

**Comment by staceyturnage** [comment]
There also needs to be some consistency throughout the site.  Some places the word "technology" is used other places the word it shortened to "tech".  Use one or the other not both.

**Comment by juliaelman** [comment]
@corinnepw assigning to you for reviewing/approving the new content.

**Comment by techibis** [comment]
Recommendation to make the first sentence an action statement instead of a passive "if you..."  And if we can create excitement while we are at it, it would be a bonus!  We want the person to want to be involved.  Suggestion:

Instead of:  If you want to contribute to the success of women in technology and women transitioning into technology careers today, your contribution will help us improve the technology’s industry’s diversity problem, NOW! 

maybe something like:  Contribute to the success of women in technology and women transitioning into technology careers today.  Your contribution will help us improve the technology industry's diversity problem, NOW!

(Submitted by a student during my Open Source class in Miami)

**Comment by corinnepw** [comment]
@techibis totally agree! Needs to be more action-oriented. Will take those comments and re-word! thanks!

**Comment by corinnepw** [comment]
Would also love to hear from @mmcelaney & @brookefuchs on donation page language!

**Comment by mmcelaney** [comment]
Thanks @corinnepw I can take a look at this issue tonight.

**Comment by gizmodesign** [comment]
Suggesting, after the first 2 sentences above:

Your donation creates a cost-effective avenue for women to gain technical knowledge. Support for Girl Develop It means it's never too late to learn — our students range in age from 18 to 70. We firmly believe in creating avenues for women to benefit from the opportunities and rewards of learning web development.

**Comment by kstack7** [comment]
Where do we stand with this page? Do we want to push these changes?

**Comment by corinnepw** [comment]
Love @gizmodesign's suggestions. Thank you! Including them in some new language for the revamped Donate page. Any extra eyes/editors much appreciated! cc @mmcelaney @brendajin @DBNess!

@alohaas Would also love any suggestions as to placement of this new text around the updates made in #397!

Our Impact
Girl Develop It empowers more than 1,000 students per month with coding skills. Our community-centered learning environments support women progressing from students to teachers to leaders and technical professionals over time. These women are changing the face of tech culture today and mentoring the young women technical leaders of tomorrow.

[below infographic elements]

Why Support Girl Develop It?
When you donate to Girl Develop It, you're supporting our mission to provide affordable, welcoming and culturally accessible educational opportunities for adult women from diverse backgrounds to learn software development skills.

Support the expansion of the work we've done since 2010 to create sustainable communities that foster women’s continued engagement in developing software and improving their technology skills.

​Help Us Grow
Your donation will support a cost-effective avenue for women to gain technical knowledge. Support for Girl Develop It means it's never too late to learn — our students range in age from 18 to 180. We firmly believe in creating avenues for women to benefit from the opportunities and rewards of learning web development. With your ​donation​, Girl Develop It ​will​ expand to ​new cities​, empowering more ​women.

​Celebrate #GDIday and Five Years of Girl Develop It!
If you donate between January​ ​12th - February 13th,​ you'll be entered to win some special gifts as part of our celebration of Girl Develop It's five year anniversary, including a custom-made Always Be Coding sweatshirt, a Girl Develop It water bottle, or a Girl Develop It sticker! 

[can we link to these photos above accordingly?]
Always Be Coding sweatshirt: ![img_1355](https://cloud.githubusercontent.com/assets/4427638/12143899/1d47065c-b452-11e5-91e4-3f686d1efee7.JPG)
GDI bottle: ![img_1353](https://cloud.githubusercontent.com/assets/4427638/12143908/2a01f546-b452-11e5-8f8c-4529aee2fef0.JPG)
GDI sticker: ![img_1360](https://cloud.githubusercontent.com/assets/4427638/12143879/f2cacc6a-b451-11e5-8a3b-da41b988ba7c.JPG)

​[At the bottom, below the final Donate button]
​
​Other ways to support:
Corporate sponsorships: Please reach out to sponsorships@girldevelopit.com for more information.
Mail: Checks made payable to Girl Develop It can be sent to: 
1522 Cole St.
Enumclaw, WA
98022

Girl Develop It is a 501(c3) not for profit organization, and all donations are tax-deductible.

**Comment by mmcelaney** [comment]
Happy to take a look at this, I should have some time today. :)

_Maureen McElaney_
_Co-Leader_
_Girl Develop It Burlington_
_Email: *burlington@girldevelopit.com
*Website:_ http://www.girldevelopit.com/
http://www.girldevelopit.com/chapters/burlington

**Comment by corinnepw** [comment]
D'oh just realized I tagged everyone but @kstack7 :smile: :wave:

**Comment by kstack7** [comment]
haha no biggie! I'm already on this thread so it's all good :wave:

**Comment by alohaas** [comment]
@corinnepw I'll have some feedback / progress tomorrow evening on this!

**Comment by kstack7** [comment]
Hey @alohaas any updates? We don't want to overlap any occurring work but we also need to get this puppy shipped soon so let us know where you're at :) thanks!

**Comment by alohaas** [comment]
@kstack7 pr coming in a few

**Comment by kstack7** [comment]
woo! thanks, @alohaas :) let me know if I can help with anything! :+1:

**Comment by alohaas** [comment]
will do :grin:

**Comment by kstack7** [comment]
Aaaaand closing! Nice job, ladies :+1:
